### PR TITLE
Tested and updated README.rst for MacOS 10.14.3 using python 3.7

### PR DESCRIPTION
**Pull request by poglesbyg**
Hi, I've installed and tested this package using MacOS 10.14.3 using python 3.7. Please let me know if you need me to specify anything else.

### CODE REVIEW

**Comment by reece** [comment]
Paul-
Thanks for the PR. I appreciate the changes to the README.

The file additions are all for your local virtual environment, which should not be part of the repo.

Please remove `bin/`, commit, and push again. Your PR will be automatically updated.

Thanks!

**Comment by poglesbyg** [comment]
Reece,
Thanks for a cool project. I've removed  `bin/` and recommitted. Please let me know if there is anything else I can do to help. I'd like to get more involved.
Best,
Paul

**Comment by reece** [comment]
You appear to have closed the PR. Was that intentional? If it's closed, I
can't merge it!

**Comment by poglesbyg** [comment]
Oh, that was not my meaning! Sorry!

**Comment by poglesbyg** [comment]
So i'm confused. Can I close this pull request now?

**Comment by reece** [comment]
Hi @poglesbyg-

I appreciate your eagerness to contribute! 

With the allele registry commit, you've essentially combined two distinct features or changes into a single PR. PRs should contain discrete changes that do one thing. So, I'm going to close this PR unmerged. I will manually add the README change.

Also, since vmc-python is a work in progress, the code will move fast and sometimes a bit chaotically. I am not ready to accept frequent PRs. When the project is further along, I'll be happy to accept changes.

-Reece

**Comment by poglesbyg** [comment]
Reece-

If you want help, or need contributors let me know. Good luck!

-Paul

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Pull request closed without merging**
